//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: hello.txt
namespace PBMessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"A")]
  public partial class A : global::ProtoBuf.IExtensible
  {
    public A() {}
    
    private int _val;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"val", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int val
    {
      get { return _val; }
      set { _val = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"B")]
  public partial class B : global::ProtoBuf.IExtensible
  {
    public B() {}
    
    private readonly global::System.Collections.Generic.List<A> _list = new global::System.Collections.Generic.List<A>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<A> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: rank.txt
namespace PBMessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GM_RankInfo")]
  public partial class GM_RankInfo : global::ProtoBuf.IExtensible
  {
    public GM_RankInfo() {}
    
    private int _m_place;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_place", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_place
    {
      get { return _m_place; }
      set { _m_place = value; }
    }
    private int _m_roleID = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"m_roleID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int m_roleID
    {
      get { return _m_roleID; }
      set { _m_roleID = value; }
    }
    private string _m_roleName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"m_roleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string m_roleName
    {
      get { return _m_roleName; }
      set { _m_roleName = value; }
    }
    private int _m_vip = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"m_vip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int m_vip
    {
      get { return _m_vip; }
      set { _m_vip = value; }
    }
    private int _m_value = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"m_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int m_value
    {
      get { return _m_value; }
      set { _m_value = value; }
    }
    private int _m_headphoto = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"m_headphoto", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int m_headphoto
    {
      get { return _m_headphoto; }
      set { _m_headphoto = value; }
    }
    private int _m_headFrame = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"m_headFrame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int m_headFrame
    {
      get { return _m_headFrame; }
      set { _m_headFrame = value; }
    }
    private string _m_qqhead = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"m_qqhead", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string m_qqhead
    {
      get { return _m_qqhead; }
      set { _m_qqhead = value; }
    }
    private string _m_nickname = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"m_nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string m_nickname
    {
      get { return _m_nickname; }
      set { _m_nickname = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GM_RankPageRequest")]
  public partial class GM_RankPageRequest : global::ProtoBuf.IExtensible
  {
    public GM_RankPageRequest() {}
    
    private int _m_RoleID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_RoleID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_RoleID
    {
      get { return _m_RoleID; }
      set { _m_RoleID = value; }
    }
    private int _m_RankType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_RankType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_RankType
    {
      get { return _m_RankType; }
      set { _m_RankType = value; }
    }
    private int _m_pagenum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"m_pagenum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_pagenum
    {
      get { return _m_pagenum; }
      set { _m_pagenum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GM_RankListReturn")]
  public partial class GM_RankListReturn : global::ProtoBuf.IExtensible
  {
    public GM_RankListReturn() {}
    
    private int _m_RankType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_RankType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_RankType
    {
      get { return _m_RankType; }
      set { _m_RankType = value; }
    }
    private GM_RankInfo _m_SelfInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"m_SelfInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public GM_RankInfo m_SelfInfo
    {
      get { return _m_SelfInfo; }
      set { _m_SelfInfo = value; }
    }
    private readonly global::System.Collections.Generic.List<GM_RankInfo> _m_RankInfo = new global::System.Collections.Generic.List<GM_RankInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"m_RankInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<GM_RankInfo> m_RankInfo
    {
      get { return _m_RankInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GM_AllRankListRequest")]
  public partial class GM_AllRankListRequest : global::ProtoBuf.IExtensible
  {
    public GM_AllRankListRequest() {}
    
    private int _m_RoleID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_RoleID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_RoleID
    {
      get { return _m_RoleID; }
      set { _m_RoleID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GM_AllRankTypeListReturn")]
  public partial class GM_AllRankTypeListReturn : global::ProtoBuf.IExtensible
  {
    public GM_AllRankTypeListReturn() {}
    
    private int _count;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private readonly global::System.Collections.Generic.List<GM_RankListReturn> _ranklist = new global::System.Collections.Generic.List<GM_RankListReturn>();
    [global::ProtoBuf.ProtoMember(2, Name=@"ranklist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<GM_RankListReturn> ranklist
    {
      get { return _ranklist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}